name: Structured Prod Dev

plugins:
  - name: solidity
    version: ">=0.4.0,<0.9"


dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.3.0
  - name: setprotocol
    github: SetProtocol/set-protocol-v2
    version: 0.11.0
